# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-31 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ascipic2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='filename',
        ),
        migrations.AddField(
            model_name='image',
            name='path',
            field=models.FileField(default='documents/', upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
