# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-31 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ascipic2', '0004_auto_20180331_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='imgascii',
            new_name='ascii',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='imgname',
            new_name='name',
        ),
    ]
